language: go
sudo: false
matrix:
  include:
  - os: osx
    go: 1.14.x
  - os: linux
    go: 1.14.x
notifications:
  email: false
script:
- curl -sL https://taskfile.dev/install.sh | sh
- ./bin/task ci
